name: File Sync

on:
  push:
    branches:
      - develop
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@v2.0.0
        with:
          REPOSITORIES: |
            jennxu118/auto-deploy@develop
            jennxu118/auto-test@develop
          FILES: |
            scrip/release_hotfix.sh=.github/script/release_hotfix.sh
          TOKEN: ${{ secrets.ACTIONS }}